-- FlexiLog Exercises Database Authoritative Overhaul - Non-Duplicate Custom Data
-- Generated on 2026-05-28

-- 1. Drop existing muscle_group constraint if exists to support new groups
ALTER TABLE exercises DROP CONSTRAINT IF EXISTS exercises_muscle_group_check;

-- 2. Create updated muscle_group constraint supporting 12 muscle groups
ALTER TABLE exercises ADD CONSTRAINT exercises_muscle_group_check 
  CHECK (muscle_group IN ('chest', 'back', 'legs', 'shoulders', 'biceps', 'triceps', 'core', 'full_body', 'glutes', 'forearms', 'traps', 'cardio'));

-- 3. Add equipment column if not exists
ALTER TABLE exercises ADD COLUMN IF NOT EXISTS equipment TEXT CHECK (equipment IN ('杠铃', '哑铃', '绳索', '器械', '自重', '壶铃', '其他'));

-- 4. Execute custom unique updates
UPDATE exercises SET description = '双脚同肩宽站立，屈髋下腰使上身呈约45度倾角，背部挺直，核心完全锁死。双手以略宽于肩的闭合正手握法紧抓杠铃杆。吸气控制重量下放至双臂伸直，背肌完全拉伸；呼气收紧核心，以肘关节后拉为支点，将重量拉向小腹位置，最高点用力向内夹紧双侧肩胛骨。', tips = '手掌不要用力抓死把手以防二头代偿，手仅作挂钩；背部始终呈直线，严禁圆背或靠身体晃动拔起重量。', equipment = '杠铃', rest_seconds = 120 WHERE id = '5c75022a-991e-441d-b83a-d862f4738d97'; -- Name: Barbell Row
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手以略宽于肩的闭合正手握法紧抓杠铃杆。屈髋屈膝下蹲，双手握杆；核心锁死，挺胸，足中足跟踩地发力，腿部与背部协同将重量拉起，保持重量紧贴腿面，至身体完全直立锁定髋关节；沿腿部缓慢屈髋下放。', tips = '拉起过程中脊柱绝不能拱起或曲挠，杠铃杆严禁离开身体，手臂完全伸直充当拉线，不可耸肩。', equipment = '杠铃', rest_seconds = 120 WHERE id = 'ce38c0f0-4148-46b6-9e3d-6125537e5f3f'; -- Name: Deadlift
UPDATE exercises SET description = '坐在固定座椅上，调整座椅高度，腰椎自然挺直，大腿被挡垫稳固固定，双脚踩实。双手分别握住拉杆或双头绳索末端卡扣。呼气背阔肌发力，肩胛骨启动下沉后收，带动双肘向身体两侧下方拉动，直至杠杆接近胸锁骨位置；吸气对抗重力阻力，缓慢将双臂送回至完全伸直。', tips = '下拉或拉起时应专注于用大肘往肋骨方向插，不要过多使用二头肌拉引，身体不要大幅度前后摇摆借力。', equipment = '绳索', rest_seconds = 60 WHERE id = 'e8724874-c93c-4339-812f-156a206a11a8'; -- Name: Lat Pulldown
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。呼气背阔肌发力，肩胛骨启动下沉后收，带动双肘向身体两侧下方拉动，直至杠杆接近胸锁骨位置；吸气对抗重力阻力，缓慢将双臂送回至完全伸直。', tips = '下拉或拉起时应专注于用大肘往肋骨方向插，不要过多使用二头肌拉引，身体不要大幅度前后摇摆借力。', equipment = '自重', rest_seconds = 60 WHERE id = '2ca1d061-7b53-46fe-92a6-61f027308b62'; -- Name: Pull-ups
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。吸气控制重量下放至双臂伸直，背肌完全拉伸；呼气收紧核心，以肘关节后拉为支点，将重量拉向小腹位置，最高点用力向内夹紧双侧肩胛骨。', tips = '手掌不要用力抓死把手以防二头代偿，手仅作挂钩；背部始终呈直线，严禁圆背或靠身体晃动拔起重量。', equipment = '其他', rest_seconds = 90 WHERE id = '807f040a-75c8-4754-bf0f-c87efaecf7f1'; -- Name: T杠划船
UPDATE exercises SET description = '平躺在训练平凳上，后脑勺、上背部、臀部以及双脚踩地保持稳定五点接触。双手持哑铃置于大腿或身体两侧，手腕保持中立稳定。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '哑铃', rest_seconds = 90 WHERE id = '12202c98-e35b-4a51-bdd6-55058f8cc508'; -- Name: 仰卧哑铃上拉
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。屈髋屈膝下蹲，双手握杆；核心锁死，挺胸，足中足跟踩地发力，腿部与背部协同将重量拉起，保持重量紧贴腿面，至身体完全直立锁定髋关节；沿腿部缓慢屈髋下放。', tips = '拉起过程中脊柱绝不能拱起或曲挠，杠铃杆严禁离开身体，手臂完全伸直充当拉线，不可耸肩。', equipment = '其他', rest_seconds = 120 WHERE id = '5081a669-5f05-46b4-8b84-04660d1910fb'; -- Name: 传统硬拉
UPDATE exercises SET description = '坐在固定座椅上，调整座椅高度，腰椎自然挺直，大腿被挡垫稳固固定，双脚踩实。双手紧握阻力把手。吸气控制重量下放至双臂伸直，背肌完全拉伸；呼气收紧核心，以肘关节后拉为支点，将重量拉向小腹位置，最高点用力向内夹紧双侧肩胛骨。', tips = '手掌不要用力抓死把手以防二头代偿，手仅作挂钩；背部始终呈直线，严禁圆背或靠身体晃动拔起重量。', equipment = '器械', rest_seconds = 90 WHERE id = 'c923c632-22d3-4ad4-8153-8beaa6db2e49'; -- Name: 单臂坐姿划船
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。呼气背阔肌发力，肩胛骨启动下沉后收，带动双肘向身体两侧下方拉动，直至杠杆接近胸锁骨位置；吸气对抗重力阻力，缓慢将双臂送回至完全伸直。', tips = '下拉或拉起时应专注于用大肘往肋骨方向插，不要过多使用二头肌拉引，身体不要大幅度前后摇摆借力。', equipment = '其他', rest_seconds = 90 WHERE id = '8205fce3-db4f-439e-a24d-0996bcc3a9d5'; -- Name: 单臂高位下拉
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '其他', rest_seconds = 90 WHERE id = 'f9d703fd-4d35-4fe0-8a7b-ef01907e774d'; -- Name: 反向飞鸟
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。呼气背阔肌发力，肩胛骨启动下沉后收，带动双肘向身体两侧下方拉动，直至杠杆接近胸锁骨位置；吸气对抗重力阻力，缓慢将双臂送回至完全伸直。', tips = '下拉或拉起时应专注于用大肘往肋骨方向插，不要过多使用二头肌拉引，身体不要大幅度前后摇摆借力。', equipment = '自重', rest_seconds = 60 WHERE id = '91140626-a05f-4014-946a-79aa47b7d368'; -- Name: 反握引体向上
UPDATE exercises SET description = '双脚同肩宽站立，屈髋下腰使上身呈约45度倾角，背部挺直，核心完全锁死。双手持哑铃置于大腿或身体两侧，手腕保持中立稳定。吸气控制重量下放至双臂伸直，背肌完全拉伸；呼气收紧核心，以肘关节后拉为支点，将重量拉向小腹位置，最高点用力向内夹紧双侧肩胛骨。', tips = '手掌不要用力抓死把手以防二头代偿，手仅作挂钩；背部始终呈直线，严禁圆背或靠身体晃动拔起重量。', equipment = '哑铃', rest_seconds = 90 WHERE id = '4d2ef2ae-d9f9-4313-b82c-e03c3bc0818a'; -- Name: 哑铃俯身划船
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手持哑铃置于大腿或身体两侧，手腕保持中立稳定。吸气控制重量下放至双臂伸直，背肌完全拉伸；呼气收紧核心，以肘关节后拉为支点，将重量拉向小腹位置，最高点用力向内夹紧双侧肩胛骨。', tips = '手掌不要用力抓死把手以防二头代偿，手仅作挂钩；背部始终呈直线，严禁圆背或靠身体晃动拔起重量。', equipment = '哑铃', rest_seconds = 90 WHERE id = 'ee975be0-991f-4e65-b0a7-71250e05723b'; -- Name: 哑铃单臂划船
UPDATE exercises SET description = '坐在固定座椅上，调整座椅高度，腰椎自然挺直，大腿被挡垫稳固固定，双脚踩实。双手紧握阻力把手。吸气控制重量下放至双臂伸直，背肌完全拉伸；呼气收紧核心，以肘关节后拉为支点，将重量拉向小腹位置，最高点用力向内夹紧双侧肩胛骨。', tips = '手掌不要用力抓死把手以防二头代偿，手仅作挂钩；背部始终呈直线，严禁圆背或靠身体晃动拔起重量。', equipment = '器械', rest_seconds = 90 WHERE id = 'ad8e7d70-aefe-42df-846b-06d41179f6d9'; -- Name: 坐姿划船（V把）
UPDATE exercises SET description = '坐在固定座椅上，调整座椅高度，腰椎自然挺直，大腿被挡垫稳固固定，双脚踩实。双手紧握阻力把手。吸气控制重量下放至双臂伸直，背肌完全拉伸；呼气收紧核心，以肘关节后拉为支点，将重量拉向小腹位置，最高点用力向内夹紧双侧肩胛骨。', tips = '手掌不要用力抓死把手以防二头代偿，手仅作挂钩；背部始终呈直线，严禁圆背或靠身体晃动拔起重量。', equipment = '器械', rest_seconds = 90 WHERE id = 'a7ca1d22-3b2d-4075-9c26-f30eb59ad3e6'; -- Name: 坐姿划船（宽握）
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。呼气背阔肌发力，肩胛骨启动下沉后收，带动双肘向身体两侧下方拉动，直至杠杆接近胸锁骨位置；吸气对抗重力阻力，缓慢将双臂送回至完全伸直。', tips = '下拉或拉起时应专注于用大肘往肋骨方向插，不要过多使用二头肌拉引，身体不要大幅度前后摇摆借力。', equipment = '自重', rest_seconds = 60 WHERE id = 'f39b042b-e2da-4677-9f01-5f91d74257ba'; -- Name: 宽握引体向上
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '其他', rest_seconds = 90 WHERE id = '1689b2a1-0130-47e4-9f15-6bdccec0b78a'; -- Name: 山羊挺身
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。呼气背阔肌发力，肩胛骨启动下沉后收，带动双肘向身体两侧下方拉动，直至杠杆接近胸锁骨位置；吸气对抗重力阻力，缓慢将双臂送回至完全伸直。', tips = '下拉或拉起时应专注于用大肘往肋骨方向插，不要过多使用二头肌拉引，身体不要大幅度前后摇摆借力。', equipment = '自重', rest_seconds = 60 WHERE id = '8a1c1480-1e42-4f1a-bfad-3ea75a65c608'; -- Name: 引体向上
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手以略宽于肩的闭合正手握法紧抓杠铃杆。吸气控制重量下放至双臂伸直，背肌完全拉伸；呼气收紧核心，以肘关节后拉为支点，将重量拉向小腹位置，最高点用力向内夹紧双侧肩胛骨。', tips = '手掌不要用力抓死把手以防二头代偿，手仅作挂钩；背部始终呈直线，严禁圆背或靠身体晃动拔起重量。', equipment = '杠铃', rest_seconds = 120 WHERE id = 'f5c4aeb3-66cc-46d9-af93-b7664ce5c455'; -- Name: 杠铃划船
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手以略宽于肩的闭合正手握法紧抓杠铃杆。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '杠铃', rest_seconds = 120 WHERE id = '4c6aacfd-9845-4468-b47e-f3d84c2f4c5e'; -- Name: 杠铃耸肩
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。屈髋屈膝下蹲，双手握杆；核心锁死，挺胸，足中足跟踩地发力，腿部与背部协同将重量拉起，保持重量紧贴腿面，至身体完全直立锁定髋关节；沿腿部缓慢屈髋下放。', tips = '拉起过程中脊柱绝不能拱起或曲挠，杠铃杆严禁离开身体，手臂完全伸直充当拉线，不可耸肩。', equipment = '其他', rest_seconds = 120 WHERE id = '37148a74-361c-4b7e-b6ed-7ce1b9fdadf4'; -- Name: 架上硬拉
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。屈髋屈膝下蹲，双手握杆；核心锁死，挺胸，足中足跟踩地发力，腿部与背部协同将重量拉起，保持重量紧贴腿面，至身体完全直立锁定髋关节；沿腿部缓慢屈髋下放。', tips = '拉起过程中脊柱绝不能拱起或曲挠，杠铃杆严禁离开身体，手臂完全伸直充当拉线，不可耸肩。', equipment = '其他', rest_seconds = 120 WHERE id = '0228bd66-0794-44ed-b446-0aeb28490fbe'; -- Name: 相扑硬拉
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。呼气背阔肌发力，肩胛骨启动下沉后收，带动双肘向身体两侧下方拉动，直至杠杆接近胸锁骨位置；吸气对抗重力阻力，缓慢将双臂送回至完全伸直。', tips = '下拉或拉起时应专注于用大肘往肋骨方向插，不要过多使用二头肌拉引，身体不要大幅度前后摇摆借力。', equipment = '自重', rest_seconds = 60 WHERE id = '0097b450-15a8-4b65-8d6d-9d2b2da05c65'; -- Name: 窄握引体向上
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手分别握住拉杆或双头绳索末端卡扣。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '绳索', rest_seconds = 60 WHERE id = 'b3cc40cc-039d-4d0c-85e0-6c99621014d0'; -- Name: 绳索直臂下压
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。膝关节微屈并锁定，维持核心收紧；屈髋发力将臀部往正后方推送，使上身前倾下放重量，保持重量贴沿腿下滑至小腿中段；呼气臀大肌前推直立，顶部收紧臀肌。', tips = '重点在于髋部的后推前后移动，而非下蹲；脊柱必须全程维持挺直中立以防下背部受伤。', equipment = '其他', rest_seconds = 120 WHERE id = '188a06be-1e92-4b04-a524-b5e29f877fd1'; -- Name: 罗马尼亚硬拉
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '其他', rest_seconds = 90 WHERE id = '53d72bc5-152e-4231-b8d2-c752ec12ddca'; -- Name: 面拉
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。呼气背阔肌发力，肩胛骨启动下沉后收，带动双肘向身体两侧下方拉动，直至杠杆接近胸锁骨位置；吸气对抗重力阻力，缓慢将双臂送回至完全伸直。', tips = '下拉或拉起时应专注于用大肘往肋骨方向插，不要过多使用二头肌拉引，身体不要大幅度前后摇摆借力。', equipment = '其他', rest_seconds = 90 WHERE id = 'edef8cbb-e92d-4084-b387-38c4154e9bcc'; -- Name: 高位下拉（反握）
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。呼气背阔肌发力，肩胛骨启动下沉后收，带动双肘向身体两侧下方拉动，直至杠杆接近胸锁骨位置；吸气对抗重力阻力，缓慢将双臂送回至完全伸直。', tips = '下拉或拉起时应专注于用大肘往肋骨方向插，不要过多使用二头肌拉引，身体不要大幅度前后摇摆借力。', equipment = '其他', rest_seconds = 90 WHERE id = '098cbeb9-63fb-4eab-9b5f-b9c238313f75'; -- Name: 高位下拉（宽握）
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。呼气背阔肌发力，肩胛骨启动下沉后收，带动双肘向身体两侧下方拉动，直至杠杆接近胸锁骨位置；吸气对抗重力阻力，缓慢将双臂送回至完全伸直。', tips = '下拉或拉起时应专注于用大肘往肋骨方向插，不要过多使用二头肌拉引，身体不要大幅度前后摇摆借力。', equipment = '其他', rest_seconds = 90 WHERE id = '969af8d0-e468-47dd-a876-46eb29d612a8'; -- Name: 高位下拉（窄握）
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '其他', rest_seconds = 90 WHERE id = '715d2e19-64a7-40c5-a4a2-6e71fdac0653'; -- Name: 21响礼炮
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手以略宽于肩的闭合正手握法紧抓杠铃杆。双手紧握重物，手肘贴住身体；呼气肱二头肌发力弯举重量，前臂靠近大臂，顶部极力收缩二头肌；吸气控制下放速度，缓慢将重力落回至手臂伸直。', tips = '前臂向外翻转（旋后）能获得更好的二头挤压；手肘要时刻锁在两侧，身体不能前后摇晃借力。', equipment = '杠铃', rest_seconds = 120 WHERE id = '316e1008-044e-4f74-89da-42709d1851f4'; -- Name: Barbell Curl
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手各持哑铃，掌心相对呈中立握姿，大臂紧贴身体。双手紧握重物，手肘贴住身体；呼气肱二头肌发力弯举重量，前臂靠近大臂，顶部极力收缩二头肌；吸气控制下放速度，缓慢将重力落回至手臂伸直。', tips = '前臂向外翻转（旋后）能获得更好的二头挤压；手肘要时刻锁在两侧，身体不能前后摇晃借力。', equipment = '哑铃', rest_seconds = 90 WHERE id = '39829aae-a450-4d67-baab-f1d27b339b10'; -- Name: Hammer Curl
UPDATE exercises SET description = '坐在30-45度倾角的训练椅上，双脚平放地面踩实，肩胛骨向后收紧下沉。双手持哑铃置于大腿或身体两侧，手腕保持中立稳定。双手紧握重物，手肘贴住身体；呼气肱二头肌发力弯举重量，前臂靠近大臂，顶部极力收缩二头肌；吸气控制下放速度，缓慢将重力落回至手臂伸直。', tips = '前臂向外翻转（旋后）能获得更好的二头挤压；手肘要时刻锁在两侧，身体不能前后摇晃借力。', equipment = '哑铃', rest_seconds = 90 WHERE id = 'c4aa0d5e-4a6e-4806-bd9a-ac84aea25a89'; -- Name: 上斜哑铃弯举
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手分别握住拉杆或双头绳索末端卡扣。双手紧握重物，手肘贴住身体；呼气肱二头肌发力弯举重量，前臂靠近大臂，顶部极力收缩二头肌；吸气控制下放速度，缓慢将重力落回至手臂伸直。', tips = '前臂向外翻转（旋后）能获得更好的二头挤压；手肘要时刻锁在两侧，身体不能前后摇晃借力。', equipment = '绳索', rest_seconds = 60 WHERE id = '563921fe-b427-4102-b741-73077a2eec87'; -- Name: 单臂绳索弯举
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手与肩同宽以掌心朝向自己的闭合反握法抓握杠铃杆。双手紧握重物，手肘贴住身体；呼气肱二头肌发力弯举重量，前臂靠近大臂，顶部极力收缩二头肌；吸气控制下放速度，缓慢将重力落回至手臂伸直。', tips = '前臂向外翻转（旋后）能获得更好的二头挤压；手肘要时刻锁在两侧，身体不能前后摇晃借力。', equipment = '杠铃', rest_seconds = 120 WHERE id = '3e748765-bbed-4ed3-b841-f4bf77ab4cbc'; -- Name: 反握杠铃弯举
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手持哑铃置于大腿或身体两侧，手腕保持中立稳定。双手紧握重物，手肘贴住身体；呼气肱二头肌发力弯举重量，前臂靠近大臂，顶部极力收缩二头肌；吸气控制下放速度，缓慢将重力落回至手臂伸直。', tips = '前臂向外翻转（旋后）能获得更好的二头挤压；手肘要时刻锁在两侧，身体不能前后摇晃借力。', equipment = '哑铃', rest_seconds = 90 WHERE id = 'ffc5390c-6695-48fb-ab47-a3642d161c74'; -- Name: 哑铃交替弯举
UPDATE exercises SET description = '身体调整好坐姿，双臂放置在斜托板上面，胸部贴紧斜板边缘保持上臂稳固。双手持哑铃置于大腿或身体两侧，手腕保持中立稳定。双手紧握重物，手肘贴住身体；呼气肱二头肌发力弯举重量，前臂靠近大臂，顶部极力收缩二头肌；吸气控制下放速度，缓慢将重力落回至手臂伸直。', tips = '前臂向外翻转（旋后）能获得更好的二头挤压；手肘要时刻锁在两侧，身体不能前后摇晃借力。', equipment = '哑铃', rest_seconds = 90 WHERE id = 'f5e89d92-135e-45b2-b377-486056ccc3b2'; -- Name: 哑铃斜托弯举
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手持哑铃置于大腿或身体两侧，手腕保持中立稳定。双手紧握重物，手肘贴住身体；呼气肱二头肌发力弯举重量，前臂靠近大臂，顶部极力收缩二头肌；吸气控制下放速度，缓慢将重力落回至手臂伸直。', tips = '前臂向外翻转（旋后）能获得更好的二头挤压；手肘要时刻锁在两侧，身体不能前后摇晃借力。', equipment = '哑铃', rest_seconds = 90 WHERE id = 'c4867424-f125-4245-972e-9026c3cbae6b'; -- Name: 哑铃蜘蛛弯举
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手各持哑铃，掌心相对呈中立握姿，大臂紧贴身体。双手紧握重物，手肘贴住身体；呼气肱二头肌发力弯举重量，前臂靠近大臂，顶部极力收缩二头肌；吸气控制下放速度，缓慢将重力落回至手臂伸直。', tips = '前臂向外翻转（旋后）能获得更好的二头挤压；手肘要时刻锁在两侧，身体不能前后摇晃借力。', equipment = '哑铃', rest_seconds = 90 WHERE id = '8304bfc8-c22d-4e24-806d-1d34c35c87cf'; -- Name: 哑铃锤式弯举
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手持哑铃置于大腿或身体两侧，手腕保持中立稳定。双手紧握重物，手肘贴住身体；呼气肱二头肌发力弯举重量，前臂靠近大臂，顶部极力收缩二头肌；吸气控制下放速度，缓慢将重力落回至手臂伸直。', tips = '前臂向外翻转（旋后）能获得更好的二头挤压；手肘要时刻锁在两侧，身体不能前后摇晃借力。', equipment = '哑铃', rest_seconds = 90 WHERE id = 'ef3a5021-4592-4019-9f3e-84fc480f0b31'; -- Name: 哑铃集中弯举
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。双手紧握重物，手肘贴住身体；呼气肱二头肌发力弯举重量，前臂靠近大臂，顶部极力收缩二头肌；吸气控制下放速度，缓慢将重力落回至手臂伸直。', tips = '前臂向外翻转（旋后）能获得更好的二头挤压；手肘要时刻锁在两侧，身体不能前后摇晃借力。', equipment = '器械', rest_seconds = 90 WHERE id = 'fbb4c278-584e-4e8d-9e74-be5ee09c321a'; -- Name: 器械弯举
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手以略宽于肩的闭合正手握法紧抓杠铃杆。双手紧握重物，手肘贴住身体；呼气肱二头肌发力弯举重量，前臂靠近大臂，顶部极力收缩二头肌；吸气控制下放速度，缓慢将重力落回至手臂伸直。', tips = '前臂向外翻转（旋后）能获得更好的二头挤压；手肘要时刻锁在两侧，身体不能前后摇晃借力。', equipment = '杠铃', rest_seconds = 120 WHERE id = 'f68977a9-18da-44ab-8f50-6478c97c93cf'; -- Name: 曲杠弯举
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手以略宽于肩的闭合正手握法紧抓杠铃杆。双手紧握重物，手肘贴住身体；呼气肱二头肌发力弯举重量，前臂靠近大臂，顶部极力收缩二头肌；吸气控制下放速度，缓慢将重力落回至手臂伸直。', tips = '前臂向外翻转（旋后）能获得更好的二头挤压；手肘要时刻锁在两侧，身体不能前后摇晃借力。', equipment = '杠铃', rest_seconds = 120 WHERE id = '90571603-2a6c-4f8b-ba0c-6193890975fb'; -- Name: 杠铃弯举
UPDATE exercises SET description = '身体调整好坐姿，双臂放置在斜托板上面，胸部贴紧斜板边缘保持上臂稳固。双手以略宽于肩的闭合正手握法紧抓杠铃杆。双手紧握重物，手肘贴住身体；呼气肱二头肌发力弯举重量，前臂靠近大臂，顶部极力收缩二头肌；吸气控制下放速度，缓慢将重力落回至手臂伸直。', tips = '前臂向外翻转（旋后）能获得更好的二头挤压；手肘要时刻锁在两侧，身体不能前后摇晃借力。', equipment = '杠铃', rest_seconds = 120 WHERE id = '1820dc72-2438-46f2-93d4-29b612c8a803'; -- Name: 杠铃斜托弯举
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手分别握住拉杆或双头绳索末端卡扣。双手紧握重物，手肘贴住身体；呼气肱二头肌发力弯举重量，前臂靠近大臂，顶部极力收缩二头肌；吸气控制下放速度，缓慢将重力落回至手臂伸直。', tips = '前臂向外翻转（旋后）能获得更好的二头挤压；手肘要时刻锁在两侧，身体不能前后摇晃借力。', equipment = '绳索', rest_seconds = 60 WHERE id = '180fccbb-23f8-4e54-acf6-cc48a7ce5a6e'; -- Name: 绳索弯举
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手分别握住拉杆或双头绳索末端卡扣。双手紧握重物，手肘贴住身体；呼气肱二头肌发力弯举重量，前臂靠近大臂，顶部极力收缩二头肌；吸气控制下放速度，缓慢将重力落回至手臂伸直。', tips = '前臂向外翻转（旋后）能获得更好的二头挤压；手肘要时刻锁在两侧，身体不能前后摇晃借力。', equipment = '绳索', rest_seconds = 60 WHERE id = 'eb26ab6d-64b8-4214-b75d-d9f1fdacdfb5'; -- Name: 绳索锤式弯举
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。调整好器械姿势与心肺负荷，核心微微收紧保护脊柱；保持稳定而均匀的有氧呼吸，有节奏地持续运动，直至规定运动时间。', tips = '脚掌落地时关节要微屈缓冲，严禁双膝内扣，运动过程中上身不要过度松垮，维持良好体态。', equipment = '其他', rest_seconds = 90 WHERE id = '52f0a5be-f469-4e36-8576-1d8092b3b53b'; -- Name: 划船机
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。调整好器械姿势与心肺负荷，核心微微收紧保护脊柱；保持稳定而均匀的有氧呼吸，有节奏地持续运动，直至规定运动时间。', tips = '脚掌落地时关节要微屈缓冲，严禁双膝内扣，运动过程中上身不要过度松垮，维持良好体态。', equipment = '其他', rest_seconds = 90 WHERE id = 'c5402974-1f63-40eb-9cfc-3b843ac92341'; -- Name: 单车
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。调整好器械姿势与心肺负荷，核心微微收紧保护脊柱；保持稳定而均匀的有氧呼吸，有节奏地持续运动，直至规定运动时间。', tips = '脚掌落地时关节要微屈缓冲，严禁双膝内扣，运动过程中上身不要过度松垮，维持良好体态。', equipment = '自重', rest_seconds = 60 WHERE id = '7720804d-a1e1-4cda-8330-7ac48170d589'; -- Name: 开合跳
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。调整好器械姿势与心肺负荷，核心微微收紧保护脊柱；保持稳定而均匀的有氧呼吸，有节奏地持续运动，直至规定运动时间。', tips = '脚掌落地时关节要微屈缓冲，严禁双膝内扣，运动过程中上身不要过度松垮，维持良好体态。', equipment = '其他', rest_seconds = 90 WHERE id = '8d76fc15-032c-49b4-868a-cbafdf1026c0'; -- Name: 椭圆机
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。调整好器械姿势与心肺负荷，核心微微收紧保护脊柱；保持稳定而均匀的有氧呼吸，有节奏地持续运动，直至规定运动时间。', tips = '脚掌落地时关节要微屈缓冲，严禁双膝内扣，运动过程中上身不要过度松垮，维持良好体态。', equipment = '其他', rest_seconds = 90 WHERE id = '3eb58d6d-290e-47c5-8577-0460e600efbc'; -- Name: 楼梯机
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。调整好器械姿势与心肺负荷，核心微微收紧保护脊柱；保持稳定而均匀的有氧呼吸，有节奏地持续运动，直至规定运动时间。', tips = '脚掌落地时关节要微屈缓冲，严禁双膝内扣，运动过程中上身不要过度松垮，维持良好体态。', equipment = '其他', rest_seconds = 90 WHERE id = '489a4950-ed7b-42f0-adf4-cc0728d57ab9'; -- Name: 跑步
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。调整好器械姿势与心肺负荷，核心微微收紧保护脊柱；保持稳定而均匀的有氧呼吸，有节奏地持续运动，直至规定运动时间。', tips = '脚掌落地时关节要微屈缓冲，严禁双膝内扣，运动过程中上身不要过度松垮，维持良好体态。', equipment = '自重', rest_seconds = 60 WHERE id = 'f7978d14-f812-4c11-8a1b-d9d32356677d'; -- Name: 跳绳
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。调整好器械姿势与心肺负荷，核心微微收紧保护脊柱；保持稳定而均匀的有氧呼吸，有节奏地持续运动，直至规定运动时间。', tips = '脚掌落地时关节要微屈缓冲，严禁双膝内扣，运动过程中上身不要过度松垮，维持良好体态。', equipment = '自重', rest_seconds = 60 WHERE id = 'c0ddaf09-efc6-4d20-895e-e102bb645069'; -- Name: 高抬腿
UPDATE exercises SET description = '平躺在训练平凳上，后脑勺、上背部、臀部以及双脚踩地保持稳定五点接触。双手以略宽于肩的闭合正手握法紧抓杠铃杆。吸气控制阻力，缓慢将重量下放至胸口位置，前臂保持垂直地面；呼气胸大肌发力，将重量推起至双臂几乎伸直，顶部用力挤压胸肌，手肘切勿锁死。', tips = '始终维持肩胛骨后缩下沉，起杠及推起过程中严禁耸肩以防止斜方肌代偿，推至顶部不要大力撞击。', equipment = '杠铃', rest_seconds = 120 WHERE id = 'e25c08a0-7d59-41ed-ac2e-fc522728ee7b'; -- Name: Bench Press
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手分别握住拉杆或双头绳索末端卡扣。手臂微屈约15度并锁死肘关节；呼气胸大肌发力，沿弧线轨迹将重量向前夹拢，使双手在胸前相遇；吸气控制阻力，缓慢将双臂沿弧线放回起始位置。', tips = '动作全程务必固定肘关节角度，用大臂靠拢的感觉带动夹胸，切勿借力做成推胸。', equipment = '绳索', rest_seconds = 60 WHERE id = '5fbe3e6d-0dba-4682-bdbe-745ba92cf676'; -- Name: Cable Flyes
UPDATE exercises SET description = '坐在30-45度倾角的训练椅上，双脚平放地面踩实，肩胛骨向后收紧下沉。双手持哑铃置于大腿或身体两侧，手腕保持中立稳定。吸气控制阻力，缓慢将重量下放至胸口位置，前臂保持垂直地面；呼气胸大肌发力，将重量推起至双臂几乎伸直，顶部用力挤压胸肌，手肘切勿锁死。', tips = '始终维持肩胛骨后缩下沉，起杠及推起过程中严禁耸肩以防止斜方肌代偿，推至顶部不要大力撞击。', equipment = '哑铃', rest_seconds = 90 WHERE id = '665ba408-51ed-4c9e-afc8-ab3b706d7315'; -- Name: Incline Dumbbell Press
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。双手比肩略宽支撑，核心收紧；吸气缓慢将身体放低至胸部几乎触地，大臂与躯干呈45度夹角；呼气胸肌与三头肌发力，将身体推回原位。', tips = '整个过程头部、脊柱与骨盆保持中立，臀部不能下塌或高耸，避免大臂向两侧打得过开伤害肩膀。', equipment = '其他', rest_seconds = 90 WHERE id = 'fd0d547c-3ea6-4e5a-9bf5-a1d83e054130'; -- Name: Push-ups
UPDATE exercises SET description = '坐在30-45度倾角的训练椅上，双脚平放地面踩实，肩胛骨向后收紧下沉。双手紧握阻力把手。双手比肩略宽支撑，核心收紧；吸气缓慢将身体放低至胸部几乎触地，大臂与躯干呈45度夹角；呼气胸肌与三头肌发力，将身体推回原位。', tips = '整个过程头部、脊柱与骨盆保持中立，臀部不能下塌或高耸，避免大臂向两侧打得过开伤害肩膀。', equipment = '自重', rest_seconds = 60 WHERE id = 'ea8d3c9d-87c1-4b84-8889-f0710f2a2a2c'; -- Name: 上斜俯卧撑
UPDATE exercises SET description = '躺在下斜板上，双脚牢牢卡住固定垫，保持核心与臀部收紧，肩胛下压。双手紧握阻力把手。双手比肩略宽支撑，核心收紧；吸气缓慢将身体放低至胸部几乎触地，大臂与躯干呈45度夹角；呼气胸肌与三头肌发力，将身体推回原位。', tips = '整个过程头部、脊柱与骨盆保持中立，臀部不能下塌或高耸，避免大臂向两侧打得过开伤害肩膀。', equipment = '自重', rest_seconds = 60 WHERE id = '6ba46cfa-ad99-47b7-a43e-d5c9faaca20a'; -- Name: 下斜俯卧撑
UPDATE exercises SET description = '平躺在训练平凳上，后脑勺、上背部、臀部以及双脚踩地保持稳定五点接触。双手持哑铃置于大腿或身体两侧，手腕保持中立稳定。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '哑铃', rest_seconds = 90 WHERE id = '82ed3585-e723-4f84-a9e4-e22f8faf9fcb'; -- Name: 仰卧哑铃直臂上拉
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。双手比肩略宽支撑，核心收紧；吸气缓慢将身体放低至胸部几乎触地，大臂与躯干呈45度夹角；呼气胸肌与三头肌发力，将身体推回原位。', tips = '整个过程头部、脊柱与骨盆保持中立，臀部不能下塌或高耸，避免大臂向两侧打得过开伤害肩膀。', equipment = '自重', rest_seconds = 60 WHERE id = '21643821-b112-443a-91ce-1cd220671a59'; -- Name: 俯卧撑
UPDATE exercises SET description = '双手握住双杠，双臂伸直支撑身体，核心收紧，大腿微屈，小腿交叉悬空。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '自重', rest_seconds = 60 WHERE id = 'b43ff699-9dea-4102-8cf4-f71f7f198e99'; -- Name: 双杠臂屈伸
UPDATE exercises SET description = '坐在30-45度倾角的训练椅上，双脚平放地面踩实，肩胛骨向后收紧下沉。双手持哑铃置于大腿或身体两侧，手腕保持中立稳定。吸气控制阻力，缓慢将重量下放至胸口位置，前臂保持垂直地面；呼气胸大肌发力，将重量推起至双臂几乎伸直，顶部用力挤压胸肌，手肘切勿锁死。', tips = '始终维持肩胛骨后缩下沉，起杠及推起过程中严禁耸肩以防止斜方肌代偿，推至顶部不要大力撞击。', equipment = '哑铃', rest_seconds = 90 WHERE id = 'a2166c35-ecbe-4393-b420-2d6a7a8edd5e'; -- Name: 哑铃上斜卧推
UPDATE exercises SET description = '坐在30-45度倾角的训练椅上，双脚平放地面踩实，肩胛骨向后收紧下沉。双手持哑铃置于大腿或身体两侧，手腕保持中立稳定。手臂微屈约15度并锁死肘关节；呼气胸大肌发力，沿弧线轨迹将重量向前夹拢，使双手在胸前相遇；吸气控制阻力，缓慢将双臂沿弧线放回起始位置。', tips = '动作全程务必固定肘关节角度，用大臂靠拢的感觉带动夹胸，切勿借力做成推胸。', equipment = '哑铃', rest_seconds = 90 WHERE id = '63e0b99c-435c-44c1-a9db-d16d43cc0a09'; -- Name: 哑铃上斜飞鸟
UPDATE exercises SET description = '躺在下斜板上，双脚牢牢卡住固定垫，保持核心与臀部收紧，肩胛下压。双手持哑铃置于大腿或身体两侧，手腕保持中立稳定。吸气控制阻力，缓慢将重量下放至胸口位置，前臂保持垂直地面；呼气胸大肌发力，将重量推起至双臂几乎伸直，顶部用力挤压胸肌，手肘切勿锁死。', tips = '始终维持肩胛骨后缩下沉，起杠及推起过程中严禁耸肩以防止斜方肌代偿，推至顶部不要大力撞击。', equipment = '哑铃', rest_seconds = 90 WHERE id = '386ff14e-de8b-4ac8-b346-6a91126067a7'; -- Name: 哑铃下斜卧推
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手持哑铃置于大腿或身体两侧，手腕保持中立稳定。吸气控制阻力，缓慢将重量下放至胸口位置，前臂保持垂直地面；呼气胸大肌发力，将重量推起至双臂几乎伸直，顶部用力挤压胸肌，手肘切勿锁死。', tips = '始终维持肩胛骨后缩下沉，起杠及推起过程中严禁耸肩以防止斜方肌代偿，推至顶部不要大力撞击。', equipment = '哑铃', rest_seconds = 90 WHERE id = 'e1377c5a-81e3-4a7f-a249-d09eecc26e3e'; -- Name: 哑铃平板卧推
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手持哑铃置于大腿或身体两侧，手腕保持中立稳定。手臂微屈约15度并锁死肘关节；呼气胸大肌发力，沿弧线轨迹将重量向前夹拢，使双手在胸前相遇；吸气控制阻力，缓慢将双臂沿弧线放回起始位置。', tips = '动作全程务必固定肘关节角度，用大臂靠拢的感觉带动夹胸，切勿借力做成推胸。', equipment = '哑铃', rest_seconds = 90 WHERE id = '65a917e4-2152-41cb-bb0c-23ca01d7b126'; -- Name: 哑铃平板飞鸟
UPDATE exercises SET description = '坐在30-45度倾角的训练椅上，双脚平放地面踩实，肩胛骨向后收紧下沉。双手紧握阻力把手。吸气控制阻力，缓慢将重量下放至胸口位置，前臂保持垂直地面；呼气胸大肌发力，将重量推起至双臂几乎伸直，顶部用力挤压胸肌，手肘切勿锁死。', tips = '始终维持肩胛骨后缩下沉，起杠及推起过程中严禁耸肩以防止斜方肌代偿，推至顶部不要大力撞击。', equipment = '器械', rest_seconds = 90 WHERE id = '3e93daeb-539e-46d4-a0b1-402cac05f5cb'; -- Name: 器械上斜推胸
UPDATE exercises SET description = '躺在下斜板上，双脚牢牢卡住固定垫，保持核心与臀部收紧，肩胛下压。双手紧握阻力把手。吸气控制阻力，缓慢将重量下放至胸口位置，前臂保持垂直地面；呼气胸大肌发力，将重量推起至双臂几乎伸直，顶部用力挤压胸肌，手肘切勿锁死。', tips = '始终维持肩胛骨后缩下沉，起杠及推起过程中严禁耸肩以防止斜方肌代偿，推至顶部不要大力撞击。', equipment = '器械', rest_seconds = 90 WHERE id = '05646841-fa97-4715-9f26-0f98f0cba9b6'; -- Name: 器械下斜推胸
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。手臂微屈约15度并锁死肘关节；呼气胸大肌发力，沿弧线轨迹将重量向前夹拢，使双手在胸前相遇；吸气控制阻力，缓慢将双臂沿弧线放回起始位置。', tips = '动作全程务必固定肘关节角度，用大臂靠拢的感觉带动夹胸，切勿借力做成推胸。', equipment = '器械', rest_seconds = 90 WHERE id = '1d2855a6-4cfb-4e57-9008-7739540f6172'; -- Name: 器械夹胸（蝴蝶机）
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。吸气控制阻力，缓慢将重量下放至胸口位置，前臂保持垂直地面；呼气胸大肌发力，将重量推起至双臂几乎伸直，顶部用力挤压胸肌，手肘切勿锁死。', tips = '始终维持肩胛骨后缩下沉，起杠及推起过程中严禁耸肩以防止斜方肌代偿，推至顶部不要大力撞击。', equipment = '器械', rest_seconds = 90 WHERE id = '4fa0632b-9cd2-4afb-b6dd-8a7e2a09a08a'; -- Name: 器械推胸
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。双手比肩略宽支撑，核心收紧；吸气缓慢将身体放低至胸部几乎触地，大臂与躯干呈45度夹角；呼气胸肌与三头肌发力，将身体推回原位。', tips = '整个过程头部、脊柱与骨盆保持中立，臀部不能下塌或高耸，避免大臂向两侧打得过开伤害肩膀。', equipment = '自重', rest_seconds = 60 WHERE id = '1631d467-15e4-4c6e-ae0b-57b14cf7380b'; -- Name: 宽距俯卧撑
UPDATE exercises SET description = '坐在30-45度倾角的训练椅上，双脚平放地面踩实，肩胛骨向后收紧下沉。双手以略宽于肩的闭合正手握法紧抓杠铃杆。吸气控制阻力，缓慢将重量下放至胸口位置，前臂保持垂直地面；呼气胸大肌发力，将重量推起至双臂几乎伸直，顶部用力挤压胸肌，手肘切勿锁死。', tips = '始终维持肩胛骨后缩下沉，起杠及推起过程中严禁耸肩以防止斜方肌代偿，推至顶部不要大力撞击。', equipment = '杠铃', rest_seconds = 120 WHERE id = 'a1361834-e691-4fa1-b840-75fdda04d57a'; -- Name: 杠铃上斜卧推
UPDATE exercises SET description = '躺在下斜板上，双脚牢牢卡住固定垫，保持核心与臀部收紧，肩胛下压。双手以略宽于肩的闭合正手握法紧抓杠铃杆。吸气控制阻力，缓慢将重量下放至胸口位置，前臂保持垂直地面；呼气胸大肌发力，将重量推起至双臂几乎伸直，顶部用力挤压胸肌，手肘切勿锁死。', tips = '始终维持肩胛骨后缩下沉，起杠及推起过程中严禁耸肩以防止斜方肌代偿，推至顶部不要大力撞击。', equipment = '杠铃', rest_seconds = 120 WHERE id = 'e0df28dc-647c-4116-be8c-7cc94d366959'; -- Name: 杠铃下斜卧推
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手以略宽于肩的闭合正手握法紧抓杠铃杆。吸气控制阻力，缓慢将重量下放至胸口位置，前臂保持垂直地面；呼气胸大肌发力，将重量推起至双臂几乎伸直，顶部用力挤压胸肌，手肘切勿锁死。', tips = '始终维持肩胛骨后缩下沉，起杠及推起过程中严禁耸肩以防止斜方肌代偿，推至顶部不要大力撞击。', equipment = '杠铃', rest_seconds = 120 WHERE id = 'd187c963-5354-4ada-813c-df28ebdf1ab7'; -- Name: 杠铃平板卧推
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手以比肩窄的握距紧紧握住杠铃杆，掌心向前或相对。吸气控制阻力，缓慢将重量下放至胸口位置，前臂保持垂直地面；呼气胸大肌发力，将重量推起至双臂几乎伸直，顶部用力挤压胸肌，手肘切勿锁死。', tips = '始终维持肩胛骨后缩下沉，起杠及推起过程中严禁耸肩以防止斜方肌代偿，推至顶部不要大力撞击。', equipment = '杠铃', rest_seconds = 120 WHERE id = '333827eb-ae13-46e3-bf20-6d8db0c4a2a3'; -- Name: 窄握杠铃卧推
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手分别握住拉杆或双头绳索末端卡扣。手臂微屈约15度并锁死肘关节；呼气胸大肌发力，沿弧线轨迹将重量向前夹拢，使双手在胸前相遇；吸气控制阻力，缓慢将双臂沿弧线放回起始位置。', tips = '动作全程务必固定肘关节角度，用大臂靠拢的感觉带动夹胸，切勿借力做成推胸。', equipment = '绳索', rest_seconds = 60 WHERE id = 'e7788f50-31fb-4605-bad4-f6d6af474af6'; -- Name: 绳索飞鸟
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。双手比肩略宽支撑，核心收紧；吸气缓慢将身体放低至胸部几乎触地，大臂与躯干呈45度夹角；呼气胸肌与三头肌发力，将身体推回原位。', tips = '整个过程头部、脊柱与骨盆保持中立，臀部不能下塌或高耸，避免大臂向两侧打得过开伤害肩膀。', equipment = '自重', rest_seconds = 60 WHERE id = 'db2f6f8c-4e5a-40b5-85df-d0e6094f6aea'; -- Name: 钻石俯卧撑
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。手臂微屈约15度并锁死肘关节；呼气胸大肌发力，沿弧线轨迹将重量向前夹拢，使双手在胸前相遇；吸气控制阻力，缓慢将双臂沿弧线放回起始位置。', tips = '动作全程务必固定肘关节角度，用大臂靠拢的感觉带动夹胸，切勿借力做成推胸。', equipment = '器械', rest_seconds = 90 WHERE id = '99fd4f20-9ad4-4ea7-a812-4edbeb925db3'; -- Name: 龙门架夹胸（中位）
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。手臂微屈约15度并锁死肘关节；呼气胸大肌发力，沿弧线轨迹将重量向前夹拢，使双手在胸前相遇；吸气控制阻力，缓慢将双臂沿弧线放回起始位置。', tips = '动作全程务必固定肘关节角度，用大臂靠拢的感觉带动夹胸，切勿借力做成推胸。', equipment = '器械', rest_seconds = 90 WHERE id = '13a5da53-f150-4708-89a4-4009d34a3bca'; -- Name: 龙门架夹胸（低位）
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。手臂微屈约15度并锁死肘关节；呼气胸大肌发力，沿弧线轨迹将重量向前夹拢，使双手在胸前相遇；吸气控制阻力，缓慢将双臂沿弧线放回起始位置。', tips = '动作全程务必固定肘关节角度，用大臂靠拢的感觉带动夹胸，切勿借力做成推胸。', equipment = '器械', rest_seconds = 90 WHERE id = '5281115c-831c-40e1-ace7-004a6cf97eb4'; -- Name: 龙门架夹胸（高位）
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。呼气核心与腹直肌发力，进行躯干的卷屈使胸椎靠近盆骨，在顶点极力挤压腹肌；吸气缓慢将躯干放低回拉伸位，背部保持微曲。', tips = '双手不要抱头生拉硬扯颈椎，专注于用腹部肌肉卷起上身，颈部保持放松。', equipment = '自重', rest_seconds = 60 WHERE id = 'cf46e17c-7b76-401e-9b51-ffcff4682b82'; -- Name: Ab轮卷腹
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手分别握住拉杆或双头绳索末端卡扣。呼气核心与腹直肌发力，进行躯干的卷屈使胸椎靠近盆骨，在顶点极力挤压腹肌；吸气缓慢将躯干放低回拉伸位，背部保持微曲。', tips = '双手不要抱头生拉硬扯颈椎，专注于用腹部肌肉卷起上身，颈部保持放松。', equipment = '绳索', rest_seconds = 60 WHERE id = 'd91fc290-7f16-451d-aa90-f15fd617bab0'; -- Name: Cable Crunch
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。呼气核心与腹直肌发力，进行躯干的卷屈使胸椎靠近盆骨，在顶点极力挤压腹肌；吸气缓慢将躯干放低回拉伸位，背部保持微曲。', tips = '双手不要抱头生拉硬扯颈椎，专注于用腹部肌肉卷起上身，颈部保持放松。', equipment = '其他', rest_seconds = 90 WHERE id = '3638d335-75ab-4fe6-9c19-5ec8080dd9f2'; -- Name: Hanging Leg Raise
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。双肘弯曲支撑于地面，肘部位于肩部正下方，双脚蹬地；腹部、臀肌与股四头肌全力收紧，维持身体呈一条完全笔直的水平线；深长匀速呼吸，维持至规定时间。', tips = '核心松懈会导致腰椎塌陷产生痛感，必须时刻维持盆骨后倾及腰腹中立收紧姿势。', equipment = '自重', rest_seconds = 60 WHERE id = '8e73e601-d953-46fe-816b-b002b9837d38'; -- Name: Plank
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。呼气核心与腹直肌发力，进行躯干的卷屈使胸椎靠近盆骨，在顶点极力挤压腹肌；吸气缓慢将躯干放低回拉伸位，背部保持微曲。', tips = '双手不要抱头生拉硬扯颈椎，专注于用腹部肌肉卷起上身，颈部保持放松。', equipment = '自重', rest_seconds = 60 WHERE id = '21a3b1c6-08ab-4d46-815d-4b3cbd5ab749'; -- Name: V字卷腹
UPDATE exercises SET description = '平躺在训练平凳上，后脑勺、上背部、臀部以及双脚踩地保持稳定五点接触。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '其他', rest_seconds = 90 WHERE id = '7a32b308-ade8-45c9-ab6e-a4398d2a7b15'; -- Name: 仰卧举腿
UPDATE exercises SET description = '平躺在训练平凳上，后脑勺、上背部、臀部以及双脚踩地保持稳定五点接触。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '其他', rest_seconds = 90 WHERE id = '5e3ce062-8af1-456b-bf13-6d61a62b9ff7'; -- Name: 仰卧交替触踝
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。双肘弯曲支撑于地面，肘部位于肩部正下方，双脚蹬地；腹部、臀肌与股四头肌全力收紧，维持身体呈一条完全笔直的水平线；深长匀速呼吸，维持至规定时间。', tips = '核心松懈会导致腰椎塌陷产生痛感，必须时刻维持盆骨后倾及腰腹中立收紧姿势。', equipment = '自重', rest_seconds = 60 WHERE id = 'b0cbcdec-b86c-4025-bf3f-dd678c456485'; -- Name: 侧平板支撑
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '其他', rest_seconds = 90 WHERE id = '0974675e-3818-44f2-8853-fc6c4b1e7b69'; -- Name: 俄罗斯转体
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。呼气核心与腹直肌发力，进行躯干的卷屈使胸椎靠近盆骨，在顶点极力挤压腹肌；吸气缓慢将躯干放低回拉伸位，背部保持微曲。', tips = '双手不要抱头生拉硬扯颈椎，专注于用腹部肌肉卷起上身，颈部保持放松。', equipment = '自重', rest_seconds = 60 WHERE id = 'a31a232f-c6aa-48dc-9bec-344c1b7beb07'; -- Name: 卷腹
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。呼气核心与腹直肌发力，进行躯干的卷屈使胸椎靠近盆骨，在顶点极力挤压腹肌；吸气缓慢将躯干放低回拉伸位，背部保持微曲。', tips = '双手不要抱头生拉硬扯颈椎，专注于用腹部肌肉卷起上身，颈部保持放松。', equipment = '自重', rest_seconds = 60 WHERE id = '418fe915-b178-434d-bdcb-829170ecfe2a'; -- Name: 反向卷腹
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。双肘弯曲支撑于地面，肘部位于肩部正下方，双脚蹬地；腹部、臀肌与股四头肌全力收紧，维持身体呈一条完全笔直的水平线；深长匀速呼吸，维持至规定时间。', tips = '核心松懈会导致腰椎塌陷产生痛感，必须时刻维持盆骨后倾及腰腹中立收紧姿势。', equipment = '自重', rest_seconds = 60 WHERE id = '66f4c684-2184-4d07-9393-6cbc028b0eed'; -- Name: 平板支撑
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '其他', rest_seconds = 90 WHERE id = '7d205dc2-31e1-485a-bc56-fd9c425e8b2e'; -- Name: 悬垂举腿
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '其他', rest_seconds = 90 WHERE id = '5f167aad-8fd9-42d3-b7c4-53c052fa0a66'; -- Name: 悬垂抬膝
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '其他', rest_seconds = 90 WHERE id = 'ca8d1a19-06c6-49a8-91fe-13f0f1e7ea6a'; -- Name: 死虫
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '自重', rest_seconds = 60 WHERE id = 'cb66a738-1a9b-47ee-85a4-25ec68b1ffa5'; -- Name: 登山者
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手分别握住拉杆或双头绳索末端卡扣。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '绳索', rest_seconds = 60 WHERE id = '89d9b02a-670e-470f-90f7-3ee16f90e934'; -- Name: 绳索伐木
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手分别握住拉杆或双头绳索末端卡扣。呼气核心与腹直肌发力，进行躯干的卷屈使胸椎靠近盆骨，在顶点极力挤压腹肌；吸气缓慢将躯干放低回拉伸位，背部保持微曲。', tips = '双手不要抱头生拉硬扯颈椎，专注于用腹部肌肉卷起上身，颈部保持放松。', equipment = '绳索', rest_seconds = 60 WHERE id = '65d2ced3-5f44-4ef7-821b-5269e039a04b'; -- Name: 绳索卷腹
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。呼气核心与腹直肌发力，进行躯干的卷屈使胸椎靠近盆骨，在顶点极力挤压腹肌；吸气缓慢将躯干放低回拉伸位，背部保持微曲。', tips = '双手不要抱头生拉硬扯颈椎，专注于用腹部肌肉卷起上身，颈部保持放松。', equipment = '自重', rest_seconds = 60 WHERE id = '78564ba8-4752-4f92-a772-1c357daca3bd'; -- Name: 自行车卷腹
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '其他', rest_seconds = 90 WHERE id = 'd1030385-52ae-4c0b-b737-8523049245c2'; -- Name: 鸟狗式
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '其他', rest_seconds = 90 WHERE id = 'fb0a6f84-0fed-48a8-8efa-52ab9863249f'; -- Name: 龙旗
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '其他', rest_seconds = 90 WHERE id = 'dc23740f-7e78-4db7-b1ce-b178f99da7eb'; -- Name: 农夫行走（握力）
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '器械', rest_seconds = 90 WHERE id = '62750629-6760-4852-89ce-c778e9f5f938'; -- Name: 反握腕弯举
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '其他', rest_seconds = 90 WHERE id = '70c0cb46-d427-41d9-bcfa-c09004a1526b'; -- Name: 手指伸展
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '其他', rest_seconds = 90 WHERE id = '3a9ba58c-d9c0-4f78-b792-5113ce14cd3a'; -- Name: 握力器
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手以略宽于肩的闭合正手握法紧抓杠铃杆。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '杠铃', rest_seconds = 120 WHERE id = '38387052-3fbb-42c4-b18f-e223828c0391'; -- Name: 杠铃卷绳
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '器械', rest_seconds = 90 WHERE id = '3cc878f0-a6f9-4412-a46c-9e366cf50f4d'; -- Name: 腕弯举
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '其他', rest_seconds = 120 WHERE id = '840eb114-85ff-4631-a28c-4ee1224a53ce'; -- Name: Clean and Press
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '其他', rest_seconds = 120 WHERE id = 'c6059d38-a8e7-474a-b2b4-aa337cf201f0'; -- Name: Turkish Get-up
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '其他', rest_seconds = 90 WHERE id = '468b2acb-f85f-4e0f-a1cc-4bb850198cdc'; -- Name: 农夫行走
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手持哑铃置于大腿或身体两侧，手腕保持中立稳定。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '哑铃', rest_seconds = 90 WHERE id = '996c7b60-263b-49ad-8b87-6f38f5d44c74'; -- Name: 哑铃推举
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '其他', rest_seconds = 90 WHERE id = '6620231d-2299-40c6-9eed-20433d568285'; -- Name: 土耳其起立
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '壶铃', rest_seconds = 60 WHERE id = '4988a7b9-7b6f-4866-8c64-29ccf2686ce6'; -- Name: 壶铃摆荡
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '壶铃', rest_seconds = 60 WHERE id = 'd055947f-13be-4edd-af49-3efb13317911'; -- Name: 壶铃深蹲推举
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '其他', rest_seconds = 90 WHERE id = '06b7c956-78ed-4c77-855a-0c960f114b0f'; -- Name: 战绳
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手以略宽于肩的闭合正手握法紧抓杠铃杆。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '杠铃', rest_seconds = 120 WHERE id = '4e96ba35-4994-453d-9a58-179a78a8c703'; -- Name: 杠铃借力推举
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手以略宽于肩的闭合正手握法紧抓杠铃杆。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '杠铃', rest_seconds = 120 WHERE id = 'fb6fb929-c186-4a8b-98f8-ade669fd79e0'; -- Name: 杠铃抓举
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手以略宽于肩的闭合正手握法紧抓杠铃杆。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '杠铃', rest_seconds = 120 WHERE id = 'a400e4a1-e144-4df7-8f39-19593cd5f3e8'; -- Name: 杠铃高翻
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '自重', rest_seconds = 60 WHERE id = 'f0bf1151-a978-47d3-ab68-208733e019c9'; -- Name: 波比跳
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '其他', rest_seconds = 90 WHERE id = 'bfddc3a0-03cd-4d61-8a62-46b9a72c132e'; -- Name: 单腿臀推
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手以略宽于肩的闭合正手握法紧抓杠铃杆。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '杠铃', rest_seconds = 120 WHERE id = '4c197e15-bd9d-4473-9152-e92b6c435b0e'; -- Name: 杠铃臀推
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '其他', rest_seconds = 90 WHERE id = '62ae151c-0351-4fa5-8085-03f8174640bd'; -- Name: 消防栓式
UPDATE exercises SET description = '自然直立站稳，双脚与肩同宽，膝关节微屈避免锁死，核心与臀肌强烈收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '其他', rest_seconds = 90 WHERE id = 'fc040c22-f57f-4b41-a6f1-eceab3b4fe1e'; -- Name: 站姿后踢腿
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '其他', rest_seconds = 90 WHERE id = 'e9783efd-9e9b-4502-b77a-65f5672328b1'; -- Name: 臀外展机
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '自重', rest_seconds = 60 WHERE id = '1f6608c4-f430-4391-9195-6499ee46c5f1'; -- Name: 臀桥（负重）
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '其他', rest_seconds = 90 WHERE id = '0f26fa85-4073-4ae6-8489-ebd4c6764097'; -- Name: 蛤蜊式
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '其他', rest_seconds = 90 WHERE id = '939b981b-3f55-4bca-8e40-448789cb666a'; -- Name: 跪姿后踢腿
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。吸气屈膝，控制阻力缓慢将挡板压低至膝关节呈90度夹角；呼气股四头肌发力将踏板推回原位；顶部保持膝关节微屈，切勿撞击或完全锁死膝盖。', tips = '脚底和臀大肌必须全程压实踏板和椅背，严禁脚跟抬起或下背悬空，否则会导致骨盆后倾受伤。', equipment = '其他', rest_seconds = 90 WHERE id = 'f6f9d0f6-69a6-4d32-9c1b-7f076a7a3eee'; -- Name: 45度腿举
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '其他', rest_seconds = 90 WHERE id = 'c48b15e7-9116-4058-adb3-fcb014d441f6'; -- Name: Calf Raises
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。抓紧握柄，呼气收紧腘绳肌发力弯起小腿，使圆垫移向臀部并在此顶峰收缩1秒；吸气缓慢将重物放回起始位置。', tips = '臀部和骨盆必须牢牢压紧在软垫上面，不要随着弯举翘起屁股或弯腰借力。', equipment = '器械', rest_seconds = 90 WHERE id = '3eea923b-66ec-45d8-8a87-a075684e9349'; -- Name: Leg Curl
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。吸气屈膝，控制阻力缓慢将挡板压低至膝关节呈90度夹角；呼气股四头肌发力将踏板推回原位；顶部保持膝关节微屈，切勿撞击或完全锁死膝盖。', tips = '脚底和臀大肌必须全程压实踏板和椅背，严禁脚跟抬起或下背悬空，否则会导致骨盆后倾受伤。', equipment = '器械', rest_seconds = 90 WHERE id = '69dbf47d-c941-40d4-a816-d3742ca403c0'; -- Name: Leg Press
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手以略宽于肩的闭合正手握法紧抓杠铃杆。膝关节微屈并锁定，维持核心收紧；屈髋发力将臀部往正后方推送，使上身前倾下放重量，保持重量贴沿腿下滑至小腿中段；呼气臀大肌前推直立，顶部收紧臀肌。', tips = '重点在于髋部的后推前后移动，而非下蹲；脊柱必须全程维持挺直中立以防下背部受伤。', equipment = '杠铃', rest_seconds = 120 WHERE id = 'e827a108-ed12-4e3c-9e7f-7a1d42d326b1'; -- Name: Romanian Deadlift
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手以略宽于肩的闭合正手握法紧抓杠铃杆。吸气核心收紧，启动屈髋屈膝动作，臀部如坐凳子般向下后方降低；下蹲至大腿与地面平行或略低，膝盖与脚尖方向一致；呼气脚底用力蹬地伸膝伸髋直立起立。', tips = '下蹲时膝盖方向绝对不能内扣，需始终朝向脚尖；背部和腰部绝对不能弯曲，保持中立脊柱。', equipment = '杠铃', rest_seconds = 120 WHERE id = '8538898f-9fdc-43c6-b1b9-8d685062152d'; -- Name: Squat
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '其他', rest_seconds = 90 WHERE id = '331c9d1a-56ad-45eb-a929-83d743a1f788'; -- Name: 侧弓步
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '其他', rest_seconds = 90 WHERE id = '32f7fa2c-2a26-4728-9cc1-eb84c71472e0'; -- Name: 保加利亚分腿蹲
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。抓紧握柄，呼气收紧腘绳肌发力弯起小腿，使圆垫移向臀部并在此顶峰收缩1秒；吸气缓慢将重物放回起始位置。', tips = '臀部和骨盆必须牢牢压紧在软垫上面，不要随着弯举翘起屁股或弯腰借力。', equipment = '器械', rest_seconds = 90 WHERE id = '5e414e00-8080-420d-8713-94c53e2e3ec2'; -- Name: 俯卧腿弯举
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。膝关节微屈并锁定，维持核心收紧；屈髋发力将臀部往正后方推送，使上身前倾下放重量，保持重量贴沿腿下滑至小腿中段；呼气臀大肌前推直立，顶部收紧臀肌。', tips = '重点在于髋部的后推前后移动，而非下蹲；脊柱必须全程维持挺直中立以防下背部受伤。', equipment = '其他', rest_seconds = 120 WHERE id = 'a3806be7-030a-4325-8195-2ba274726081'; -- Name: 单腿罗马尼亚硬拉
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。吸气屈膝，控制阻力缓慢将挡板压低至膝关节呈90度夹角；呼气股四头肌发力将踏板推回原位；顶部保持膝关节微屈，切勿撞击或完全锁死膝盖。', tips = '脚底和臀大肌必须全程压实踏板和椅背，严禁脚跟抬起或下背悬空，否则会导致骨盆后倾受伤。', equipment = '其他', rest_seconds = 90 WHERE id = 'cb8e5a52-6641-43a5-bb9f-32352ed16e0e'; -- Name: 单腿腿举
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '自重', rest_seconds = 60 WHERE id = '52fd03a0-1d1d-4778-baa1-12ca8293e62e'; -- Name: 单腿臀桥
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。吸气核心收紧，启动屈髋屈膝动作，臀部如坐凳子般向下后方降低；下蹲至大腿与地面平行或略低，膝盖与脚尖方向一致；呼气脚底用力蹬地伸膝伸髋直立起立。', tips = '下蹲时膝盖方向绝对不能内扣，需始终朝向脚尖；背部和腰部绝对不能弯曲，保持中立脊柱。', equipment = '器械', rest_seconds = 90 WHERE id = '285e5518-9562-4193-a848-6653d26626c4'; -- Name: 史密斯深蹲
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。吸气核心收紧，启动屈髋屈膝动作，臀部如坐凳子般向下后方降低；下蹲至大腿与地面平行或略低，膝盖与脚尖方向一致；呼气脚底用力蹬地伸膝伸髋直立起立。', tips = '下蹲时膝盖方向绝对不能内扣，需始终朝向脚尖；背部和腰部绝对不能弯曲，保持中立脊柱。', equipment = '其他', rest_seconds = 90 WHERE id = '7f47a44d-05d8-479e-b686-772365b66e00'; -- Name: 哈克深蹲
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手持哑铃置于大腿或身体两侧，手腕保持中立稳定。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '哑铃', rest_seconds = 90 WHERE id = '7e6539b2-2f65-45ff-8fd7-4764cb75bba4'; -- Name: 哑铃箭步蹲
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手持哑铃置于大腿或身体两侧，手腕保持中立稳定。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '哑铃', rest_seconds = 90 WHERE id = '8c4cd4b6-a32d-419d-8134-8e4c2b191ff6'; -- Name: 哑铃行走箭步
UPDATE exercises SET description = '坐在固定座椅上，调整座椅高度，腰椎自然挺直，大腿被挡垫稳固固定，双脚踩实。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '器械', rest_seconds = 90 WHERE id = '72ae72d0-43b4-4dfc-b35e-e8741621201d'; -- Name: 坐姿提踵
UPDATE exercises SET description = '坐在固定座椅上，调整座椅高度，腰椎自然挺直，大腿被挡垫稳固固定，双脚踩实。双手紧握阻力把手。抓紧握柄，呼气收紧腘绳肌发力弯起小腿，使圆垫移向臀部并在此顶峰收缩1秒；吸气缓慢将重物放回起始位置。', tips = '臀部和骨盆必须牢牢压紧在软垫上面，不要随着弯举翘起屁股或弯腰借力。', equipment = '器械', rest_seconds = 90 WHERE id = '998724dc-bf47-4fb4-aa0a-6235e21980ce'; -- Name: 坐姿腿弯举
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手以略宽于肩的闭合正手握法紧抓杠铃杆。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '杠铃', rest_seconds = 120 WHERE id = '87c9c9a8-43db-402c-b139-c0e9350c35f8'; -- Name: 杠铃前蹲
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手以略宽于肩的闭合正手握法紧抓杠铃杆。吸气核心收紧，启动屈髋屈膝动作，臀部如坐凳子般向下后方降低；下蹲至大腿与地面平行或略低，膝盖与脚尖方向一致；呼气脚底用力蹬地伸膝伸髋直立起立。', tips = '下蹲时膝盖方向绝对不能内扣，需始终朝向脚尖；背部和腰部绝对不能弯曲，保持中立脊柱。', equipment = '杠铃', rest_seconds = 120 WHERE id = 'f4ec05fa-fae5-4d99-a3f0-b466779d3267'; -- Name: 杠铃深蹲
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手以略宽于肩的闭合正手握法紧抓杠铃杆。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '杠铃', rest_seconds = 120 WHERE id = '87e64ca7-c85e-4f2f-b372-54fcb6c6dd59'; -- Name: 杠铃箭步蹲
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。屈髋屈膝下蹲，双手握杆；核心锁死，挺胸，足中足跟踩地发力，腿部与背部协同将重量拉起，保持重量紧贴腿面，至身体完全直立锁定髋关节；沿腿部缓慢屈髋下放。', tips = '拉起过程中脊柱绝不能拱起或曲挠，杠铃杆严禁离开身体，手臂完全伸直充当拉线，不可耸肩。', equipment = '其他', rest_seconds = 120 WHERE id = 'cc5b6a35-725e-4e50-ab2f-a0a3daf6204d'; -- Name: 直腿硬拉
UPDATE exercises SET description = '自然直立站稳，双脚与肩同宽，膝关节微屈避免锁死，核心与臀肌强烈收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '器械', rest_seconds = 90 WHERE id = '3f5ff712-c4dc-4ac5-a259-32f621cdc54c'; -- Name: 站姿提踵
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。膝关节微屈并锁定，维持核心收紧；屈髋发力将臀部往正后方推送，使上身前倾下放重量，保持重量贴沿腿下滑至小腿中段；呼气臀大肌前推直立，顶部收紧臀肌。', tips = '重点在于髋部的后推前后移动，而非下蹲；脊柱必须全程维持挺直中立以防下背部受伤。', equipment = '其他', rest_seconds = 120 WHERE id = 'c2ace4c8-d601-4955-a0fc-8f34d6ac7533'; -- Name: 罗马尼亚硬拉
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。吸气屈膝，控制阻力缓慢将挡板压低至膝关节呈90度夹角；呼气股四头肌发力将踏板推回原位；顶部保持膝关节微屈，切勿撞击或完全锁死膝盖。', tips = '脚底和臀大肌必须全程压实踏板和椅背，严禁脚跟抬起或下背悬空，否则会导致骨盆后倾受伤。', equipment = '其他', rest_seconds = 90 WHERE id = '75d9cf8a-7f44-4c8b-a064-de1a70530707'; -- Name: 腿举
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '其他', rest_seconds = 90 WHERE id = 'bbaf4eec-70ba-4dea-a1ab-80e44830d18a'; -- Name: 腿内收
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '其他', rest_seconds = 90 WHERE id = 'c4c542d0-ebdc-4425-b0c1-5ac4ec67594a'; -- Name: 腿外展
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '其他', rest_seconds = 90 WHERE id = '0ddd348b-0b4b-44a4-ad8d-10757610c1f7'; -- Name: 腿屈伸
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。抓紧握柄，呼气收紧腘绳肌发力弯起小腿，使圆垫移向臀部并在此顶峰收缩1秒；吸气缓慢将重物放回起始位置。', tips = '臀部和骨盆必须牢牢压紧在软垫上面，不要随着弯举翘起屁股或弯腰借力。', equipment = '器械', rest_seconds = 90 WHERE id = '271c11a9-349f-4eb6-af1c-2a1905ce9d1b'; -- Name: 腿弯举
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '其他', rest_seconds = 90 WHERE id = '0c29920b-493d-499e-bb23-97d031901a45'; -- Name: 臀推
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '自重', rest_seconds = 60 WHERE id = 'c153a6b2-a8d4-448f-8935-e5013ad2801f'; -- Name: 臀桥
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '其他', rest_seconds = 90 WHERE id = '1dd28f01-9957-44b9-9797-a1a2c3cfabeb'; -- Name: 蚌式开合
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。吸气核心收紧，启动屈髋屈膝动作，臀部如坐凳子般向下后方降低；下蹲至大腿与地面平行或略低，膝盖与脚尖方向一致；呼气脚底用力蹬地伸膝伸髋直立起立。', tips = '下蹲时膝盖方向绝对不能内扣，需始终朝向脚尖；背部和腰部绝对不能弯曲，保持中立脊柱。', equipment = '其他', rest_seconds = 90 WHERE id = 'e9a1c487-8dd7-4a43-abb1-b8f993b04c48'; -- Name: 酒杯深蹲
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '器械', rest_seconds = 90 WHERE id = 'f2e7064d-d8f9-41e3-9bd7-78bc92c3ccde'; -- Name: 驴式提踵
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。吸气核心收紧，启动屈髋屈膝动作，臀部如坐凳子般向下后方降低；下蹲至大腿与地面平行或略低，膝盖与脚尖方向一致；呼气脚底用力蹬地伸膝伸髋直立起立。', tips = '下蹲时膝盖方向绝对不能内扣，需始终朝向脚尖；背部和腰部绝对不能弯曲，保持中立脊柱。', equipment = '其他', rest_seconds = 90 WHERE id = 'e0f77d17-2e5c-45c3-b4d5-0c7b6fd6b2ad'; -- Name: 高脚杯深蹲
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手分别握住拉杆或双头绳索末端卡扣。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '绳索', rest_seconds = 60 WHERE id = '4c8e6ad9-e138-4c81-a9da-325bf061755c'; -- Name: Face Pulls
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手持哑铃置于大腿或身体两侧，手腕保持中立稳定。双肘保持微屈10度并固定；呼气三角肌中束发力，将手臂向两侧弧线抬起，直至大臂与地面平行；吸气控制重力将重量放回大腿两侧。', tips = '动作全程大拇指微朝下或手腕略低于肘部，三角肌发力，切勿耸肩以免斜方肌代偿。', equipment = '哑铃', rest_seconds = 90 WHERE id = 'ac0baefb-97b6-426c-a676-abb9bd65103c'; -- Name: Lateral Raises
UPDATE exercises SET description = '自然直立站稳，双脚与肩同宽，膝关节微屈避免锁死，核心与臀肌强烈收紧。双手以略宽于肩的闭合正手握法紧抓杠铃杆。呼气肩部三角肌发力，将重量垂直向上推起至手臂完全伸直，头部微后仰以避开轨迹；吸气控制阻力，将重量缓慢下放至肩颈位置。', tips = '推至顶部时手肘可以伸直但不要撞击或完全锁死锁死；腹肌和臀肌要始终夹紧，防止腰椎超展挺腰。', equipment = '杠铃', rest_seconds = 120 WHERE id = '4a354dee-aea8-4171-9e52-4fdead2e9865'; -- Name: Overhead Press
UPDATE exercises SET description = '双脚同肩宽站立，屈髋下腰使上身呈约45度倾角，背部挺直，核心完全锁死。双手持哑铃置于大腿或身体两侧，手腕保持中立稳定。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '哑铃', rest_seconds = 90 WHERE id = 'ad504560-5311-41da-b3ac-17305b72384d'; -- Name: 俯身哑铃飞鸟
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手持哑铃置于大腿或身体两侧，手腕保持中立稳定。双肘保持微屈10度并固定；呼气三角肌中束发力，将手臂向两侧弧线抬起，直至大臂与地面平行；吸气控制重力将重量放回大腿两侧。', tips = '动作全程大拇指微朝下或手腕略低于肘部，三角肌发力，切勿耸肩以免斜方肌代偿。', equipment = '哑铃', rest_seconds = 90 WHERE id = '0101323b-85a4-4b52-a110-5f68e51b02bb'; -- Name: 单臂哑铃侧平举
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '器械', rest_seconds = 90 WHERE id = '54c28247-dbc7-4de9-bbbd-78337eefe4e2'; -- Name: 反向蝴蝶机
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手持哑铃置于大腿或身体两侧，手腕保持中立稳定。双肘保持微屈10度并固定；呼气三角肌中束发力，将手臂向两侧弧线抬起，直至大臂与地面平行；吸气控制重力将重量放回大腿两侧。', tips = '动作全程大拇指微朝下或手腕略低于肘部，三角肌发力，切勿耸肩以免斜方肌代偿。', equipment = '哑铃', rest_seconds = 90 WHERE id = 'db89551a-b4f8-4f0c-8d96-07b25235119c'; -- Name: 哑铃侧平举
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手持哑铃置于大腿或身体两侧，手腕保持中立稳定。双肘保持微屈10度并固定；呼气三角肌中束发力，将手臂向两侧弧线抬起，直至大臂与地面平行；吸气控制重力将重量放回大腿两侧。', tips = '动作全程大拇指微朝下或手腕略低于肘部，三角肌发力，切勿耸肩以免斜方肌代偿。', equipment = '哑铃', rest_seconds = 90 WHERE id = '1065f281-32cf-46a5-b19d-1f6c20031fc7'; -- Name: 哑铃前平举
UPDATE exercises SET description = '坐在固定座椅上，调整座椅高度，腰椎自然挺直，大腿被挡垫稳固固定，双脚踩实。双手持哑铃置于大腿或身体两侧，手腕保持中立稳定。呼气肩部三角肌发力，将重量垂直向上推起至手臂完全伸直，头部微后仰以避开轨迹；吸气控制阻力，将重量缓慢下放至肩颈位置。', tips = '推至顶部时手肘可以伸直但不要撞击或完全锁死锁死；腹肌和臀肌要始终夹紧，防止腰椎超展挺腰。', equipment = '哑铃', rest_seconds = 90 WHERE id = 'a7be3206-cb50-44fd-94c1-bce7d2c29074'; -- Name: 哑铃坐姿推举
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手持哑铃置于大腿或身体两侧，手腕保持中立稳定。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '哑铃', rest_seconds = 90 WHERE id = 'fbbf86e5-b645-4faa-a91d-52747e1c6ec0'; -- Name: 哑铃直立划船
UPDATE exercises SET description = '自然直立站稳，双脚与肩同宽，膝关节微屈避免锁死，核心与臀肌强烈收紧。双手持哑铃置于大腿或身体两侧，手腕保持中立稳定。呼气肩部三角肌发力，将重量垂直向上推起至手臂完全伸直，头部微后仰以避开轨迹；吸气控制阻力，将重量缓慢下放至肩颈位置。', tips = '推至顶部时手肘可以伸直但不要撞击或完全锁死锁死；腹肌和臀肌要始终夹紧，防止腰椎超展挺腰。', equipment = '哑铃', rest_seconds = 90 WHERE id = 'bbbfe7b2-437c-4a69-9740-d73e5e234068'; -- Name: 哑铃站姿推举
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手持哑铃置于大腿或身体两侧，手腕保持中立稳定。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '哑铃', rest_seconds = 90 WHERE id = '2d2b1124-2e5a-4ab1-8702-934d12a1fdf8'; -- Name: 哑铃耸肩
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。双肘保持微屈10度并固定；呼气三角肌中束发力，将手臂向两侧弧线抬起，直至大臂与地面平行；吸气控制重力将重量放回大腿两侧。', tips = '动作全程大拇指微朝下或手腕略低于肘部，三角肌发力，切勿耸肩以免斜方肌代偿。', equipment = '器械', rest_seconds = 90 WHERE id = '9d017178-e7c5-4aa7-b696-5f526c04ca86'; -- Name: 器械侧平举
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。呼气肩部三角肌发力，将重量垂直向上推起至手臂完全伸直，头部微后仰以避开轨迹；吸气控制阻力，将重量缓慢下放至肩颈位置。', tips = '推至顶部时手肘可以伸直但不要撞击或完全锁死锁死；腹肌和臀肌要始终夹紧，防止腰椎超展挺腰。', equipment = '器械', rest_seconds = 90 WHERE id = 'fd950f9d-04c0-4607-9a63-6f6f62181a8d'; -- Name: 器械推举
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。呼气肩部三角肌发力，将重量垂直向上推起至手臂完全伸直，头部微后仰以避开轨迹；吸气控制阻力，将重量缓慢下放至肩颈位置。', tips = '推至顶部时手肘可以伸直但不要撞击或完全锁死锁死；腹肌和臀肌要始终夹紧，防止腰椎超展挺腰。', equipment = '其他', rest_seconds = 90 WHERE id = 'c189647e-63a3-466b-b47f-fb28a677d6c0'; -- Name: 地雷管推举
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手以略宽于肩的闭合正手握法紧抓杠铃杆。双肘保持微屈10度并固定；呼气三角肌中束发力，将手臂向两侧弧线抬起，直至大臂与地面平行；吸气控制重力将重量放回大腿两侧。', tips = '动作全程大拇指微朝下或手腕略低于肘部，三角肌发力，切勿耸肩以免斜方肌代偿。', equipment = '杠铃', rest_seconds = 120 WHERE id = '5adb412f-f49a-4876-8ed6-34180a677693'; -- Name: 杠铃前平举
UPDATE exercises SET description = '坐在固定座椅上，调整座椅高度，腰椎自然挺直，大腿被挡垫稳固固定，双脚踩实。双手以略宽于肩的闭合正手握法紧抓杠铃杆。呼气肩部三角肌发力，将重量垂直向上推起至手臂完全伸直，头部微后仰以避开轨迹；吸气控制阻力，将重量缓慢下放至肩颈位置。', tips = '推至顶部时手肘可以伸直但不要撞击或完全锁死锁死；腹肌和臀肌要始终夹紧，防止腰椎超展挺腰。', equipment = '杠铃', rest_seconds = 120 WHERE id = '511a3f18-0bad-4ed9-8ddd-eff95e96daf2'; -- Name: 杠铃坐姿推举
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手以略宽于肩的闭合正手握法紧抓杠铃杆。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '杠铃', rest_seconds = 120 WHERE id = 'd0786f60-e0a8-4a01-8ba9-9254406b0fa4'; -- Name: 杠铃直立划船
UPDATE exercises SET description = '自然直立站稳，双脚与肩同宽，膝关节微屈避免锁死，核心与臀肌强烈收紧。双手以略宽于肩的闭合正手握法紧抓杠铃杆。呼气肩部三角肌发力，将重量垂直向上推起至手臂完全伸直，头部微后仰以避开轨迹；吸气控制阻力，将重量缓慢下放至肩颈位置。', tips = '推至顶部时手肘可以伸直但不要撞击或完全锁死锁死；腹肌和臀肌要始终夹紧，防止腰椎超展挺腰。', equipment = '杠铃', rest_seconds = 120 WHERE id = '48ab7238-34d4-456f-a83f-e40794150e5f'; -- Name: 杠铃站姿推举
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手分别握住拉杆或双头绳索末端卡扣。双肘保持微屈10度并固定；呼气三角肌中束发力，将手臂向两侧弧线抬起，直至大臂与地面平行；吸气控制重力将重量放回大腿两侧。', tips = '动作全程大拇指微朝下或手腕略低于肘部，三角肌发力，切勿耸肩以免斜方肌代偿。', equipment = '绳索', rest_seconds = 60 WHERE id = 'f08b7d6e-852b-4c40-a95d-6fbff8faefad'; -- Name: 绳索侧平举
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手分别握住拉杆或双头绳索末端卡扣。双肘保持微屈10度并固定；呼气三角肌中束发力，将手臂向两侧弧线抬起，直至大臂与地面平行；吸气控制重力将重量放回大腿两侧。', tips = '动作全程大拇指微朝下或手腕略低于肘部，三角肌发力，切勿耸肩以免斜方肌代偿。', equipment = '绳索', rest_seconds = 60 WHERE id = 'cc5844b5-46c0-4778-a030-d476590ffff5'; -- Name: 绳索前平举
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手分别握住拉杆或双头绳索末端卡扣。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '绳索', rest_seconds = 60 WHERE id = '44788ea8-e69c-446e-bfda-d26766b0b41d'; -- Name: 绳索面拉（后束）
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。呼气肩部三角肌发力，将重量垂直向上推起至手臂完全伸直，头部微后仰以避开轨迹；吸气控制阻力，将重量缓慢下放至肩颈位置。', tips = '推至顶部时手肘可以伸直但不要撞击或完全锁死锁死；腹肌和臀肌要始终夹紧，防止腰椎超展挺腰。', equipment = '其他', rest_seconds = 90 WHERE id = '813469ef-7190-4805-a83b-1e76d905d0a8'; -- Name: 阿诺德推举
UPDATE exercises SET description = '坐在30-45度倾角的训练椅上，双脚平放地面踩实，肩胛骨向后收紧下沉。双手持哑铃置于大腿或身体两侧，手腕保持中立稳定。双臂保持完全伸直；呼气斜方肌发力，垂直向上提起肩膀耸起至最高点，挤压斜方肌；吸气控制重力缓慢下放至拉伸位。', tips = '肩关节动作轨迹必须保持纯粹垂直的上下移动，绝对不能做前后旋转动作，防止肩峰挤压和肩袖损伤。', equipment = '哑铃', rest_seconds = 90 WHERE id = '0cc223c6-9d6d-46d5-94ed-47ee53408426'; -- Name: 上斜哑铃耸肩
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手持哑铃置于大腿或身体两侧，手腕保持中立稳定。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '哑铃', rest_seconds = 90 WHERE id = 'a6b8ad24-e7f6-46ef-9c7d-cbee2c6ff5de'; -- Name: 哑铃直立划船
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手持哑铃置于大腿或身体两侧，手腕保持中立稳定。双臂保持完全伸直；呼气斜方肌发力，垂直向上提起肩膀耸起至最高点，挤压斜方肌；吸气控制重力缓慢下放至拉伸位。', tips = '肩关节动作轨迹必须保持纯粹垂直的上下移动，绝对不能做前后旋转动作，防止肩峰挤压和肩袖损伤。', equipment = '哑铃', rest_seconds = 90 WHERE id = 'b137e88f-be00-48a1-b614-096e2b43dbca'; -- Name: 哑铃耸肩
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手以略宽于肩的闭合正手握法紧抓杠铃杆。双臂保持完全伸直；呼气斜方肌发力，垂直向上提起肩膀耸起至最高点，挤压斜方肌；吸气控制重力缓慢下放至拉伸位。', tips = '肩关节动作轨迹必须保持纯粹垂直的上下移动，绝对不能做前后旋转动作，防止肩峰挤压和肩袖损伤。', equipment = '杠铃', rest_seconds = 120 WHERE id = '8b3f8195-024f-4f26-8366-b3a37d6fa655'; -- Name: 杠铃耸肩
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手分别握住拉杆或双头绳索末端卡扣。双臂保持完全伸直；呼气斜方肌发力，垂直向上提起肩膀耸起至最高点，挤压斜方肌；吸气控制重力缓慢下放至拉伸位。', tips = '肩关节动作轨迹必须保持纯粹垂直的上下移动，绝对不能做前后旋转动作，防止肩峰挤压和肩袖损伤。', equipment = '绳索', rest_seconds = 60 WHERE id = '0d6c5bcf-374b-49c2-8583-361e75c81c7e'; -- Name: 绳索耸肩
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手以略宽于肩的闭合正手握法紧抓杠铃杆。双臂保持完全伸直；呼气斜方肌发力，垂直向上提起肩膀耸起至最高点，挤压斜方肌；吸气控制重力缓慢下放至拉伸位。', tips = '肩关节动作轨迹必须保持纯粹垂直的上下移动，绝对不能做前后旋转动作，防止肩峰挤压和肩袖损伤。', equipment = '杠铃', rest_seconds = 120 WHERE id = '676b470d-3570-48ad-b8ac-11607f2ea647'; -- Name: 背后杠铃耸肩
UPDATE exercises SET description = '平躺在训练平凳上，后脑勺、上背部、臀部以及双脚踩地保持稳定五点接触。双手紧握阻力把手。双手持重物双臂伸直，大臂微往头部方向倾斜；吸气保持大臂绝对固定，屈肘将重量下放至额头或发际线位置；呼气三头肌发力将手臂推直还原。', tips = '手肘必须在动作过程中保持向内夹紧，不能向两侧过度张开，防止负荷转移到关节上。', equipment = '其他', rest_seconds = 90 WHERE id = '610be830-79a0-4c13-9727-d2124f3f0831'; -- Name: Skull Crushers
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手分别握住拉杆或双头绳索末端卡扣。双手握住拉绳，手肘弯曲成90度紧贴身体；呼气肱三头肌发力，将前臂垂直向下压至手臂完全伸直，底部极力收缩三头肌；吸气控制拉力缓慢曲肘折回。', tips = '大臂和手肘在动作全程绝对不能发生任何晃动，肩膀放松，切勿用身体的重力压上去。', equipment = '绳索', rest_seconds = 60 WHERE id = '19e5c9d4-a092-44a0-aaed-4493546d713c'; -- Name: Tricep Pushdown
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。双手握住拉绳，手肘弯曲成90度紧贴身体；呼气肱三头肌发力，将前臂垂直向下压至手臂完全伸直，底部极力收缩三头肌；吸气控制拉力缓慢曲肘折回。', tips = '大臂和手肘在动作全程绝对不能发生任何晃动，肩膀放松，切勿用身体的重力压上去。', equipment = '其他', rest_seconds = 90 WHERE id = 'fbe07173-1552-4922-ac3c-57e7830c2e2d'; -- Name: V把下压
UPDATE exercises SET description = '平躺在训练平凳上，后脑勺、上背部、臀部以及双脚踩地保持稳定五点接触。双手持哑铃置于大腿或身体两侧，手腕保持中立稳定。双手持重物双臂伸直，大臂微往头部方向倾斜；吸气保持大臂绝对固定，屈肘将重量下放至额头或发际线位置；呼气三头肌发力将手臂推直还原。', tips = '手肘必须在动作过程中保持向内夹紧，不能向两侧过度张开，防止负荷转移到关节上。', equipment = '哑铃', rest_seconds = 90 WHERE id = '3bb7c0cb-3e73-43fe-9617-452087ec9212'; -- Name: 仰卧哑铃臂屈伸
UPDATE exercises SET description = '平躺在训练平凳上，后脑勺、上背部、臀部以及双脚踩地保持稳定五点接触。双手紧握阻力把手。双手持重物双臂伸直，大臂微往头部方向倾斜；吸气保持大臂绝对固定，屈肘将重量下放至额头或发际线位置；呼气三头肌发力将手臂推直还原。', tips = '手肘必须在动作过程中保持向内夹紧，不能向两侧过度张开，防止负荷转移到关节上。', equipment = '其他', rest_seconds = 90 WHERE id = 'c009e55b-4d20-42c2-ac59-2f9af08e1dec'; -- Name: 仰卧臂屈伸
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。双手持重物双臂伸直，大臂微往头部方向倾斜；吸气保持大臂绝对固定，屈肘将重量下放至额头或发际线位置；呼气三头肌发力将手臂推直还原。', tips = '手肘必须在动作过程中保持向内夹紧，不能向两侧过度张开，防止负荷转移到关节上。', equipment = '其他', rest_seconds = 90 WHERE id = 'd65afc1c-941c-4e45-841c-f07823ef14df'; -- Name: 凳上臂屈伸
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手分别握住拉杆或双头绳索末端卡扣。双手握住拉绳，手肘弯曲成90度紧贴身体；呼气肱三头肌发力，将前臂垂直向下压至手臂完全伸直，底部极力收缩三头肌；吸气控制拉力缓慢曲肘折回。', tips = '大臂和手肘在动作全程绝对不能发生任何晃动，肩膀放松，切勿用身体的重力压上去。', equipment = '绳索', rest_seconds = 60 WHERE id = '2987c5e5-ebea-449c-9def-cd86ea7de316'; -- Name: 单臂绳索下压
UPDATE exercises SET description = '双手握住双杠，双臂伸直支撑身体，核心收紧，大腿微屈，小腿交叉悬空。双手紧握阻力把手。双手持重物双臂伸直，大臂微往头部方向倾斜；吸气保持大臂绝对固定，屈肘将重量下放至额头或发际线位置；呼气三头肌发力将手臂推直还原。', tips = '手肘必须在动作过程中保持向内夹紧，不能向两侧过度张开，防止负荷转移到关节上。', equipment = '自重', rest_seconds = 60 WHERE id = '0a0c3659-7ea7-441b-be4c-7e0742376d6e'; -- Name: 双杠臂屈伸（三头）
UPDATE exercises SET description = '双脚同肩宽站立，屈髋下腰使上身呈约45度倾角，背部挺直，核心完全锁死。双手持哑铃置于大腿或身体两侧，手腕保持中立稳定。双手持重物双臂伸直，大臂微往头部方向倾斜；吸气保持大臂绝对固定，屈肘将重量下放至额头或发际线位置；呼气三头肌发力将手臂推直还原。', tips = '手肘必须在动作过程中保持向内夹紧，不能向两侧过度张开，防止负荷转移到关节上。', equipment = '哑铃', rest_seconds = 90 WHERE id = '0ede40f2-8bc3-49d6-a60a-b3aaa7e1edd6'; -- Name: 哑铃俯身臂屈伸
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手持哑铃置于大腿或身体两侧，手腕保持中立稳定。双手持重物双臂伸直，大臂微往头部方向倾斜；吸气保持大臂绝对固定，屈肘将重量下放至额头或发际线位置；呼气三头肌发力将手臂推直还原。', tips = '手肘必须在动作过程中保持向内夹紧，不能向两侧过度张开，防止负荷转移到关节上。', equipment = '哑铃', rest_seconds = 90 WHERE id = 'a2bbb2bb-ec60-4c81-a4d5-a40702228427'; -- Name: 哑铃过头臂屈伸
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。双手持重物双臂伸直，大臂微往头部方向倾斜；吸气保持大臂绝对固定，屈肘将重量下放至额头或发际线位置；呼气三头肌发力将手臂推直还原。', tips = '手肘必须在动作过程中保持向内夹紧，不能向两侧过度张开，防止负荷转移到关节上。', equipment = '器械', rest_seconds = 90 WHERE id = 'e02c53c7-a1d0-4b7a-85ef-5d3d94c1b75e'; -- Name: 器械臂屈伸
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '其他', rest_seconds = 90 WHERE id = '79dc9083-434b-4949-b36c-856815a9cc21'; -- Name: 窄握卧推
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手分别握住拉杆或双头绳索末端卡扣。双手握住拉绳，手肘弯曲成90度紧贴身体；呼气肱三头肌发力，将前臂垂直向下压至手臂完全伸直，底部极力收缩三头肌；吸气控制拉力缓慢曲肘折回。', tips = '大臂和手肘在动作全程绝对不能发生任何晃动，肩膀放松，切勿用身体的重力压上去。', equipment = '绳索', rest_seconds = 60 WHERE id = 'da008b5c-60bc-4417-8772-5a749a5e4750'; -- Name: 绳索Y型下压
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手分别握住拉杆或双头绳索末端卡扣。双手握住拉绳，手肘弯曲成90度紧贴身体；呼气肱三头肌发力，将前臂垂直向下压至手臂完全伸直，底部极力收缩三头肌；吸气控制拉力缓慢曲肘折回。', tips = '大臂和手肘在动作全程绝对不能发生任何晃动，肩膀放松，切勿用身体的重力压上去。', equipment = '绳索', rest_seconds = 60 WHERE id = '91e5377d-166e-4767-84d3-91c493533b00'; -- Name: 绳索下压
UPDATE exercises SET description = '身体调整好坐姿，双臂放置在斜托板上面，胸部贴紧斜板边缘保持上臂稳固。双手分别握住拉杆或双头绳索末端卡扣。双手持重物双臂伸直，大臂微往头部方向倾斜；吸气保持大臂绝对固定，屈肘将重量下放至额头或发际线位置；呼气三头肌发力将手臂推直还原。', tips = '手肘必须在动作过程中保持向内夹紧，不能向两侧过度张开，防止负荷转移到关节上。', equipment = '绳索', rest_seconds = 60 WHERE id = '783f483a-d72b-434a-8569-d8cacbf9fbb1'; -- Name: 绳索斜托臂屈伸
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手分别握住拉杆或双头绳索末端卡扣。双手持重物双臂伸直，大臂微往头部方向倾斜；吸气保持大臂绝对固定，屈肘将重量下放至额头或发际线位置；呼气三头肌发力将手臂推直还原。', tips = '手肘必须在动作过程中保持向内夹紧，不能向两侧过度张开，防止负荷转移到关节上。', equipment = '绳索', rest_seconds = 60 WHERE id = '958638d3-fd8d-40f4-b584-2c4d43f83e18'; -- Name: 绳索过头臂屈伸
UPDATE exercises SET description = '准备好器械，身体保持稳定状态，核心收紧。双手紧握阻力把手。配合呼吸，缓慢地拉起或推起重量，动作顶点主动挤压肌肉，随后控制速度放回。', tips = '动作全程保持核心紧张，下放速度要慢，切勿耸肩借力或依靠惯性甩动重量。', equipment = '自重', rest_seconds = 60 WHERE id = 'de5bcbb9-0583-48a2-9b25-4ef464c1e5a7'; -- Name: 钻石俯卧撑