'use server'

import { createClient } from '@/lib/supabase/server'
import { revalidatePath } from 'next/cache'
import { PlanData, DayPlan, ExercisePlan } from '@/types'

export async function savePlanAsTemplate(plan: PlanData) {
  try {
    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()
    
    if (!user) {
      return { error: 'Not authenticated' }
    }

    // Normalize weight fields: convert weight_ref/weight to weight_kg (number)
    const normalizeWeight = (ex: ExercisePlan) => {
      if (ex.weight_kg != null && typeof ex.weight_kg === 'number' && ex.weight_kg > 0) return ex.weight_kg
      if (ex.weight_kg != null && typeof ex.weight_kg === 'string') {
        const n = parseFloat(ex.weight_kg)
        if (!isNaN(n) && n > 0) return n
      }
      if (ex.weight != null && typeof ex.weight === 'number' && ex.weight > 0) return ex.weight
      // Parse weight_ref like "55-75kg" → take lower bound
      const ref = ex.weight_ref || ex.weight_kg || ex.weight
      if (ref && typeof ref === 'string') {
        const match = ref.match(/(\d+)/)
        if (match) return parseInt(match[1])
      }
      return undefined
    }

    // Normalize all exercises in all days
    const normalizedDays = (plan.days || []).map((day: DayPlan) => ({
      ...day,
      exercises: (day.exercises || []).map((ex: ExercisePlan) => {
        const weight_kg = normalizeWeight(ex)
        const { weight_ref, weight, ...rest } = ex
        return weight_kg != null ? { ...rest, weight_kg } : rest
      }),
    }))

    // Save as template
    const { data: template, error } = await supabase
      .from('workout_templates')
      .insert({
        name: plan.name || 'AI Training Plan',
        description: plan.description || 'Generated by AI Coach',
        exercises: normalizedDays,
        user_id: user.id,
      })
      .select()
      .single()

    if (error) {
      console.error('Save template error:', error)
      return { error: error.message }
    }

    revalidatePath('/workout')
    return { data: template }
  } catch (e) {
    console.error('savePlanAsTemplate error:', e)
    return { error: '操作失败' }
  }
}

export async function getTemplates() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  
  if (!user) {
    return { data: [] }
  }

  const { data } = await supabase
    .from('workout_templates')
    .select('*')
    .eq('user_id', user.id)
    .order('created_at', { ascending: false })

  return { data: data || [] }
}

export async function deleteTemplate(templateId: string) {
  try {
    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()
    
    if (!user) {
      return { error: 'Not authenticated' }
    }

    const { error } = await supabase
      .from('workout_templates')
      .delete()
      .eq('id', templateId)
      .eq('user_id', user.id)

    if (error) {
      return { error: error.message }
    }

    revalidatePath('/workout')
    return { success: true }
  } catch (e) {
    console.error('deleteTemplate error:', e)
    return { error: '操作失败' }
  }
}

export async function renameTemplate(templateId: string, newName: string) {
  try {
    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()
    
    if (!user) {
      return { error: 'Not authenticated' }
    }

    const { error } = await supabase
      .from('workout_templates')
      .update({ name: newName })
      .eq('id', templateId)
      .eq('user_id', user.id)

    if (error) {
      return { error: error.message }
    }

    revalidatePath('/workout')
    return { success: true }
  } catch (e) {
    console.error('renameTemplate error:', e)
    return { error: '操作失败' }
  }
}
