'use server'

import { createClient } from '@/lib/supabase/server'
import { revalidatePath } from 'next/cache'

export async function savePlanAsTemplate(plan: any) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  
  if (!user) {
    return { error: 'Not authenticated' }
  }

  // Save as template
  const { data: template, error } = await supabase
    .from('workout_templates')
    .insert({
      name: plan.name || 'AI Training Plan',
      description: plan.description || 'Generated by AI Coach',
      exercises: plan.days || [],
      user_id: user.id,
    })
    .select()
    .single()

  if (error) {
    console.error('Save template error:', error)
    return { error: error.message }
  }

  revalidatePath('/workout')
  return { data: template }
}

export async function getTemplates() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  
  if (!user) {
    return { data: [] }
  }

  const { data } = await supabase
    .from('workout_templates')
    .select('*')
    .eq('user_id', user.id)
    .order('created_at', { ascending: false })

  return { data: data || [] }
}

export async function deleteTemplate(templateId: string) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  
  if (!user) {
    return { error: 'Not authenticated' }
  }

  const { error } = await supabase
    .from('workout_templates')
    .delete()
    .eq('id', templateId)
    .eq('user_id', user.id)

  if (error) {
    return { error: error.message }
  }

  revalidatePath('/workout')
  return { success: true }
}
